import random
import numpy as np

"""
Code taken from junyanz implementation of CycleGAN
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/image_pool.py
"""

class ImagePool():
    def __init__(self, pool_size):
        self.pool_size = pool_size

        if self.pool_size > 0: # create an empty pool
            self.num_images = 0
            self.images = []

    def query(self, images):
        """
        Retrieve images from the pool.

        Args:
            images: A numpy array representing the latest images generated by the Generator
        Returns:
            return_images: A numpy array containing images queried from the pool
        """
        if self.pool_size == 0: # do nothing if buffer size is 0
            return images

        return_images = []

        for image in images:
            if self.num_images < self.pool_size:
                self.num_images += 1
                self.images.append(image)
                return_images.append(image)
            else:
                p = random.uniform(0, 1)
                if p > 0.5:
                    idx = random.randint(0, self.pool_size - 1)
                    tmp = self.images[idx]
                    self.images[idx] = image
                    return_images.append(tmp)
                else:
                    return_images.append(image)

        return_images = np.stack(return_images)

        return return_images
